# Generated by Django 5.1.1 on 2024-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('content', models.TextField(max_length=200, verbose_name='contenido')),
                ('image', models.ImageField(upload_to='servicio', verbose_name='imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creada')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='actualizada')),
            ],
            options={
                'verbose_name': 'market',
                'verbose_name_plural': 'markets',
            },
        ),
    ]
